server:
  port: 9991    

spring:
  profiles:
    active: "dev"       
       
---       
spring:
  profiles: dev
  
  devtools:
      restart:
          enabled: true
      livereload:
          enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    group-id: ics
    topic: test
    bootstrap-servers-motor: localhost:9092
    
kafka-consumer:
   transacao: test
kafka-producer:
   motor: transacao
  
  


    
